### ISSUE TITLE
Lazy image with low quality placeholder

### ISSUE THREAD

**Issue by tomaszbujnowicz** [estrattonbailey/lazim#2]
Would it be possible (somehow) to have an image placeholder just before the real image loads?
It's just so the content area doesn't jump when images are loading.

**Comment by estrattonbailey** [comment]
@tomaszbujnowicz great question! Right now, no. We could rework this library a bit to load the image in memory, instead of using the actual DOM node. That should be pretty easy.

If that was in place, it would look like this:
```html
<div class="image" data-src="{{ image | img_url: '2500x' }}">
  <img src="{{ image | img_url: '200x' }}" />
</div>
```

**Comment by tomaszbujnowicz** [comment]
Thanks, let's close that for now.
